# require an issue template to be chosen
blank_issues_enabled: false

contact_links:
  - name: multimodelity Documentation
    url: https://multimodelity.sh/docs
    about: Check if your issue/documentation is already answered in docs
